spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss?jdbcCompliantTruncation=false
    username: root
    password: Indian@123$%
    driver-class-name: com.mysql.cj.jdbc.Driver
  #hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  main:
    allow-bean-definition-overriding: true
# jwt:
#   secret: javainuse
